function fig_defaults()
%FIG_DEFAULTS Journal figure style: Times New Roman, vector-friendly.
%   Call once at the top of every figure script.

set(groot, ...
    'defaultAxesFontName',      'Times New Roman', ...
    'defaultTextFontName',      'Times New Roman', ...
    'defaultLegendFontName',    'Times New Roman', ...
    'defaultColorbarFontName',  'Times New Roman', ...
    'defaultAxesFontSize',      10, ...
    'defaultTextFontSize',      10, ...
    'defaultLegendFontSize',    9, ...
    'defaultLineLineWidth',     1.3, ...
    'defaultLineMarkerSize',    6, ...
    'defaultAxesLineWidth',     0.7, ...
    'defaultAxesTickDir',       'out', ...
    'defaultAxesBox',           'on', ...
    'defaultAxesXGrid',         'off', ...
    'defaultAxesYGrid',         'off', ...
    'defaultFigureColor',       'w', ...
    'defaultLegendBox',         'off');

% Colour-blind-safe palette (Okabe-Ito), used in condition order.
set(groot, 'defaultAxesColorOrder', [ ...
      0    114  178;   % blue
    213     94    0;   % vermillion
      0    158  115;   % bluish green
    230    159    0;   % orange
    204    121  167;   % reddish purple
     86    180  233;   % sky blue
      0      0    0]/255);
end
